### ISSUE TITLE
Setup kanban board

### ISSUE THREAD

**Issue by Nuri1977** [Nuri1977/catalog-of-my-things#19]
### Setup kanban board
Here is a link to the project: [Set](https://github.com/Nuri1977/catalog-of-my-things/projects/2)
We are three members working on this project:
1.  Team member one is @mugishasam123 
2. Team member two is @guerreiropedr0 
3. Team member three is @Nuri1977

**Comment by mikethreels** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Required Changes ♻️
- [ ] for the group tasks you made one card and put all the bullet points of the list inside it as a description, however, the idea is that every bullet point in this list should be a separate card so we have:
  - a card for Create Item class in a separate .rb file.
  - a card for All Item class properties visible in the diagram should be defined
  - a card for Adding all methods visible in the diagram.
  - a card for Implementing methods
  - a card for creating a main.rb file that will serve as your console app entry-point.
  - a card for Implementing startup actions
- [ ] the above point should apply to the cards per team member as well if there is a bullet point in [the list](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) it should be a separate card in the kanban board.
- [ ] the task of setting up the kanban board doesn't have to be a card.
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by dasileker** [comment]
### **Hi @Nuri1977,** 

### **Congratulations! 🎉**

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 : 
 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
